### ISSUE TITLE
Defaults for some tokenData properties

### ISSUE THREAD

**Issue by aoberoi** [opentok/token-encoder#1]
Currently, `encodeToken()` is completely unaware of the semantics of a token, it simply knows how to transform the inputs into something that looks like a token. This is very flexible.

This comes with the burden that the client has to know the semantics and specify all parts of the `tokenData`.

A compromise between that burden and the flexibility, one that achieves more usability, is to use default values for properties that are not defined on `tokenData`. This includes `create_time`, `expire_time`, `nonce`, and `role`.

**Comment by wobbals** [comment]
Where's Ben Pedrick when you need him? I propose we create an alias for infinite expiry times.

**Comment by aoberoi** [comment]
got enough feedback, this is getting implemented.

**Comment by aoberoi** [comment]
@wobbals :trollface:
