### ISSUE TITLE
Throw when `session_id` is not specified.

### ISSUE THREAD

**Issue by aoberoi** [opentok/token-encoder#2]
Following with #1, if the semantics of a token are implemented, then another useful behavior might be to throw when the one required property of `tokenData`, that is `session_id`, is not specified.

The one drawback I can think of is that some specs or tests might purposely want to leave out the `session_id`. I don't think this is a common case.

A possible compromise is to create an additional argument, called `options`, which can have a property called `strict`. If `strict` is truthy, then the `tokenData` is taken literally, with no default substitution and no throwing.

**Comment by aoberoi** [comment]
personally, :-1:

**Comment by ggarber** [comment]
We have that type of test already:

```
  it("should return 404 when using a null sessionId", function(done) {
```

**Comment by ggarber** [comment]
-1 strict

**Comment by omnoms** [comment]
-1. 5 year old question. This could be closed as no-fix.

**Comment by michaeljolley** [comment]
This module does not check for the validity of the data being encoded into the token. It doesn't know about the OpenTok REST API semantics, and you can encode data that doesn't result in a valid token. Its merely a utility. Use the OpenTok Node Server SDK for a more complete module.

You can find more about [generating tokens in the Node Server SDK here.](https://github.com/opentok/opentok-node#generating-tokens)

An example of using the Node Server SDK to generate the token is below:
```JS
// Generate a Token from just a sessionId (fetched from a database)
token = opentok.generateToken(sessionId);

// Generate a Token from a session object (returned from createSession)
token = session.generateToken();

// Set some options in a Token
token = session.generateToken({
  role: "moderator",
  expireTime: new Date().getTime() / 1000 + 7 * 24 * 60 * 60, // in one week
  data: "name=Johnny",
  initialLayoutClassList: ["focus"],
});
```
