### ISSUE TITLE
Add a validate method

### ISSUE THREAD

**Issue by crrobinson14** [opentok/token-encoder#3]
It would be nice to have a "validate" method that took a token and verified that it was legitimate for a given session ID and properly signed. I know OpenTok must do this itself server-side, but neither this library nor the OpenTok node-js library provide one. I could send a PR for it but wanted to check with you here first in case you thought it would be more appropriate to submit to the opentok NodeJS SDK project.

**Comment by omnoms** [comment]
Sounds good. Would be a good fail-early/catch-early kind of feature. Not that it's the true validator, since that still happens server-side. But it would help client-side to pre-emptively know if the request would fail before doing it.

**Comment by michaeljolley** [comment]
This is an interesting idea that would probably best live in the [opentok-node](https://github.com/opentok/opentok-node) repo. Feel free to submit an issue in that repository.
