### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Playfrog4u** [opentok/token-encoder#7]
I ask since the dependencies are not up to date and is giving me some feedback on npm audit

Thanks and kind regards,

**Comment by omnoms** [comment]
The project is active, just not a very active community. Yet. Make a PR with the updates or you know... @MichaelJolley could do it on stream. !ohmy

**Comment by michaeljolley** [comment]
Hi @Playfrog4u.  The dependencies for the repo have now been updated.  However, we are using an older version of tap for our tests to ensure compatibility with node version 0.10 and up.
